### ISSUE TITLE
Status of groovy scripting with ES-1.4.x

### ISSUE THREAD

**Issue by konradkonrad** [elastic/elasticsearch-river-couchdb#102]
Hi!
I am trying to figure out, what options I have to use groovy scripts in the couchdb-river with ES 1.4.x. Last time I tried (~March), I could not get the river to accept the `"script_file"`-parameter in order to use static scripts. Is that supposed to work? The README is a little unclear in that regard, unfortunately.
It would be really nice if you could shed some light on this :)

Cheers,
Konrad

**Comment by dadoonet** [comment]
No it supports only inlined scripts.

**Comment by konradkonrad** [comment]
Thx!

**Comment by jernejc** [comment]
No longterm plan to support this ?

**Comment by dadoonet** [comment]
Rivers are removed for elasticsearch 2.0.0 so we won't add new features to this project.
Checkout the couchdb input for logstash instead. It will allow you much more flexibility to manipulate your documents.

**Comment by jernejc** [comment]
Thanks for the quick response!

I was looking into logstash a bit, but it looks very new and doesn't seem to support scripts at this time, or am I missing something?

**Comment by dadoonet** [comment]
You don't need "scripts" in logstash as you have a lot of filters which can help manipulate your data.
BTW Logstash is not "new" and is widely use in production.
I'd recommend asking questions on discuss.elastic.co BTW so you can get more answers from the community than here.
