### ISSUE TITLE
Multiple ES documents per CouchDB document

### ISSUE THREAD

**Issue by antplant** [elastic/elasticsearch-river-couchdb#92]
Is there currently any way - using script filters or otherwise - to index multiple variations of a single document? For example, suppose I have a CouchDB doc like:

    {
        "_id" : "1",
        "someField" : "xyz",
        "variations" : [
            "A" : {
                "Name" : "Foo",
                "Description" : "Bar"
            },
            "B" : {
                "Name" : "Fu",
                "Description" : "Baa"
            }
        ]
    }

I'd like to flatten out `variations.A` and `variations.B` at index time, resulting in multiple ES docs of the form:

    {
        "_id" : "1",
        "someField" : "xyz",
        "variation" : "A",
        "Name" : "Foo"
    }

Is there any way of achieving this with the CouchDB river?

**Comment by dadoonet** [comment]
May be with a script? 

That said as rivers has been deprecated, I would look at logstash-input-couchdb plugin which will give you more flexibility than the river plugin.
