### ISSUE TITLE
How to turn off date detection

### ISSUE THREAD

**Issue by jkleinsc** [elastic/elasticsearch-river-couchdb#94]
Is there a way to turn off date detection when documents are mapped from couch?  I see in the Elasticsearch documentation that "date_detection": false can be specified in the mapping, but I can't figure out how to pass this through the plugin.

**Comment by dadoonet** [comment]
You need to define your mapping first (before creating the river).
Something like:

```
PUT mycouchindex/type/_mapping
{
    "type" : {
        "date_detection" : false
    }
}
```

Then create the river.

**Comment by jkleinsc** [comment]
Perfect! Thanks!
